### ISSUE TITLE
Can't install VocalForge['text'].

### ISSUE THREAD

**Issue by bobz5460** [rioharper/VocalForge#10]
Not sure if this is a dumb question and i'm just doing something wrong but when I run `pip install VocalForge['text']` it returns with:
 ```ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_vendor\packaging\requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_vendor\pyparsing\core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pip._vendor.pyparsing.exceptions.ParseException: Expected string_end, found '['  (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 344, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 411, in get_requirements
    req_to_add = install_req_from_line(
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_internal\req\constructors.py", line 393, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_internal\req\constructors.py", line 332, in parse_req_from_line
    extras = convert_extras(extras_as_string)
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_internal\req\constructors.py", line 57, in convert_extras
    return get_requirement("placeholder" + extras.lower()).extras
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_internal\utils\packaging.py", line 45, in get_requirement
    return Requirement(req_string)
  File "C:\Users\bobz5\anaconda3\lib\site-packages\pip\_vendor\packaging\requirements.py", line 104, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at ""['text']"": Expected string_end
```
help would be appreciated, thanks!

**Comment by rioharper** [comment]
Hm, thats strange, but not dumb! For whatever reason the syntax for windows vs linux anaconda is different. If you install with `pip install VocalForge[text]`, removing the quotation marks, it works like a charm on windows. I didn't know that! Ill have to update the documentation.

Thanks for bringing this to my attention!

**Comment by bobz5460** [comment]
Indeed worked like a charm, thank you!
